### ISSUE TITLE
Error Compiling on Windows 10 Ver. 22H2 (Build 19045.3570) with MSVC 2202 Community

### ISSUE THREAD

**Issue by devilkingsatan666** [till-s/epics-labca#7]
Dear developers,

I was trying to build with EPICS 7.0.7 and couldn't get around the last error saying:
`error LNK2019: unresolved external symbol lcaMexGblInit referenced in function mexFunction`

I firstly sourced a file called `windows.bat` included in EPICS Base before compiling and then got an error saying:
`No rule to make target 'gitstring.c', needed by 'gitstring.obj'.`
I manually fixed it by simply renaming the file `gitstring.c.new` to `gitstring.c`. After a few steps forward, the "unresolved external symbol" error mentioned above popped up. My Strawberry Perl is installed according to the procedure of [compiling EPICS on windows-x64 machines with MSVC](https://docs.epics-controls.org/en/latest/getting-started/installation-windows-plain.html).  Any help is appreciated!

The following is the full output:

```
C:\Program Files\LabCA>make
The system cannot find the path specified.
fatal: not a git repository (or any of the parent directories): .git
C:/ProgramData/chocolatey/lib/make/tools/install/bin/make.exe -C ./configure install
make[1]: Entering directory 'C:/Program Files/LabCA/configure'
The system cannot find the path specified.
perl -CSD C:/Users/ultrafast/EPICS/base/bin/windows-x64/makeMakefile.pl O.windows-x64 ../..
perl -CSD -MExtUtils::Command -e mkpath O.Common
C:/ProgramData/chocolatey/lib/make/tools/install/bin/make.exe -C O.windows-x64 -f ../Makefile TOP=../.. \
    T_A=windows-x64 install
make[2]: Entering directory 'C:/Program Files/LabCA/configure/O.windows-x64'
The system cannot find the path specified.
perl -CSD C:/Users/ultrafast/EPICS/base/bin/windows-x64/convertRelease.pl checkRelease
echo MEXEXT=.mexw64 >>MATLAB_CONFIG_INCLUDE
make[2]: Leaving directory 'C:/Program Files/LabCA/configure/O.windows-x64'
make[1]: Leaving directory 'C:/Program Files/LabCA/configure'
C:/ProgramData/chocolatey/lib/make/tools/install/bin/make.exe -C ./ezca install
make[1]: Entering directory 'C:/Program Files/LabCA/ezca'
The system cannot find the path specified.
perl -CSD C:/Users/ultrafast/EPICS/base/bin/windows-x64/makeMakefile.pl O.windows-x64 ../..
perl -CSD -MExtUtils::Command -e mkpath O.Common
C:/ProgramData/chocolatey/lib/make/tools/install/bin/make.exe -C O.windows-x64 -f ../Makefile TOP=../.. \
    T_A=windows-x64 install
make[2]: Entering directory 'C:/Program Files/LabCA/ezca/O.windows-x64'
The system cannot find the path specified.
perl -CSD C:/Users/ultrafast/EPICS/base/bin/windows-x64/mkmf.pl  -m ezca.d -I. -I../O.Common -I. -I. -I.. -I../../include/compiler/msvc -I../../include/os/WIN32 -I../../include -IC:\Users\ultrafast\EPICS\base/include/compiler/msvc -IC:\Users\ultrafast\EPICS\base/include/os/WIN32 -IC:\Users\ultrafast\EPICS\base/include                 ezca.obj ../ezca.c
The system cannot find the path specified.
cl               -nologo -FC -D__STDC__=0 -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE    -Ox -GL -Oy-   -W3        -MD -DEPICS_BUILD_DLL -DEPICS_CALL_DLL    -I. -I../O.Common -I. -I. -I.. -I../../include/compiler/msvc -I../../include/os/WIN32 -I../../include -IC:\Users\ultrafast\EPICS\base/include/compiler/msvc -IC:\Users\ultrafast\EPICS\base/include/os/WIN32 -IC:\Users\ultrafast\EPICS\base/include                 -c ../ezca.c
ezca.c
C:\Program Files\LabCA\ezca\ezca.c(570): warning C4311: 'type cast': pointer truncation from 'epicsThreadId' to 'unsigned long'
C:\Program Files\LabCA\ezca\ezca.c(575): warning C4311: 'type cast': pointer truncation from 'epicsThreadId' to 'unsigned long'
C:\Program Files\LabCA\ezca\ezca.c(612): warning C4311: 'type cast': pointer truncation from 'epicsThreadId' to 'unsigned long'
C:\Program Files\LabCA\ezca\ezca.c(618): warning C4311: 'type cast': pointer truncation from 'epicsThreadId' to 'unsigned long'
C:\Program Files\LabCA\ezca\ezca.c(713): warning C4311: 'type cast': pointer truncation from 'epicsThreadId' to 'unsigned long'
C:\Program Files\LabCA\ezca\ezca.c(715): warning C4311: 'type cast': pointer truncation from 'epicsThreadId' to 'unsigned long'
C:\Program Files\LabCA\ezca\ezca.c(4905): warning C4311: 'type cast': pointer truncation from 'epicsThreadId' to 'unsigned long'
C:\Program Files\LabCA\ezca\ezca.c(4934): warning C4311: 'type cast': pointer truncation from 'epicsThreadId' to 'unsigned long'
C:\Program Files\LabCA\ezca\ezca.c(5032): warning C4311: 'type cast': pointer truncation from 'epicsThreadId' to 'unsigned long'
C:\Program Files\LabCA\ezca\ezca.c(5034): warning C4311: 'type cast': pointer truncation from 'epicsThreadId' to 'unsigned long'
C:\Program Files\LabCA\ezca\ezca.c(5529): warning C4311: 'type cast': pointer truncation from 'epicsThreadId' to 'unsigned long'
C:\Program Files\LabCA\ezca\ezca.c(5546): warning C4311: 'type cast': pointer truncation from 'epicsThreadId' to 'unsigned long'
C:\Program Files\LabCA\ezca\ezca.c(5590): warning C4311: 'type cast': pointer truncation from 'epicsThreadId' to 'unsigned long'
C:\Program Files\LabCA\ezca\ezca.c(5595): warning C4311: 'type cast': pointer truncation from 'epicsThreadId' to 'unsigned long'
C:\Program Files\LabCA\ezca\ezca.c(5697): warning C4311: 'type cast': pointer truncation from 'epicsThreadId' to 'unsigned long'
C:\Program Files\LabCA\ezca\ezca.c(5716): warning C4311: 'type cast': pointer truncation from 'epicsThreadId' to 'unsigned long'
C:\Program Files\LabCA\ezca\ezca.c(5755): warning C4311: 'type cast': pointer truncation from 'epicsThreadId' to 'unsigned long'
C:\Program Files\LabCA\ezca\ezca.c(6963): warning C4311: 'type cast': pointer truncation from 'epicsThreadId' to 'unsigned long'
C:\Program Files\LabCA\ezca\ezca.c(6999): warning C4311: 'type cast': pointer truncation from 'epicsThreadId' to 'unsigned long'
C:\Program Files\LabCA\ezca\ezca.c(7191): warning C4311: 'type cast': pointer truncation from 'epicsThreadId' to 'unsigned long'
C:\Program Files\LabCA\ezca\ezca.c(7217): warning C4311: 'type cast': pointer truncation from 'epicsThreadId' to 'unsigned long'
C:\Program Files\LabCA\ezca\ezca.c(7263): warning C4311: 'type cast': pointer truncation from 'epicsThreadId' to 'unsigned long'
link -nologo -subsystem:windows -dll -LTCG -incremental:no -opt:ref -release  -MACHINE:X64      -out:ezcamt.dll -implib:ezcamt.lib    ezca.obj        C:\Users\ultrafast\EPICS\base/lib/windows-x64/ca.lib  C:\Users\ultrafast\EPICS\base/lib/windows-x64/Com.lib
   Creating library ezcamt.lib and object ezcamt.exp
Generating code
Finished generating code
"Installing shared library ../../bin/windows-x64/ezcamt.dll"
mkdir ../../bin
mkdir ../../bin/windows-x64
"Installing library ../../lib/windows-x64/ezcamt.lib"
make[2]: Leaving directory 'C:/Program Files/LabCA/ezca/O.windows-x64'
make[1]: Leaving directory 'C:/Program Files/LabCA/ezca'
C:/ProgramData/chocolatey/lib/make/tools/install/bin/make.exe -C ./glue install
make[1]: Entering directory 'C:/Program Files/LabCA/glue'
The system cannot find the path specified.
perl -CSD C:/Users/ultrafast/EPICS/base/bin/windows-x64/makeMakefile.pl O.windows-x64 ../..
perl -CSD -MExtUtils::Command -e mkpath O.Common
C:/ProgramData/chocolatey/lib/make/tools/install/bin/make.exe -C O.windows-x64 -f ../Makefile TOP=../.. \
    T_A=windows-x64 install
make[2]: Entering directory 'C:/Program Files/LabCA/glue/O.windows-x64'
The system cannot find the path specified.
perl -CSD C:/Users/ultrafast/EPICS/base/bin/windows-x64/mkmf.pl  -m mglue.d -I. -I../O.Common -I. -I. -I.. -I../../include/compiler/msvc -I../../include/os/WIN32 -I../../include -IC:\Users\ultrafast\EPICS\base/include/compiler/msvc -IC:\Users\ultrafast\EPICS\base/include/os/WIN32 -IC:\Users\ultrafast\EPICS\base/include             -I../../ezca -I../..\..\MATLAB\R2022a/extern/include    mglue.obj ../mglue.c
perl -CSD -MExtUtils::Command -e rm_f gitstring.c.new
perl > gitstring.c.new -e "print(\"const char *gitRevisionString = \\\"labca_3_8_1 - ef74a39\\\";\n\")" > gitstring.c.new
perl -MFile::Compare -e 'exit( compare(@ARGV[0],@ARGV[1]) )' gitstring.c.new gitstring.c || (perl -CSD -MExtUtils::Command -e rm_f gitstring.c; perl -e 'rename("gitstring.c.new","gitstring.c")')
') was unexpected at this time.
perl -CSD C:/Users/ultrafast/EPICS/base/bin/windows-x64/mkmf.pl  -m ctrlC-polled.d -I. -I../O.Common -I. -I. -I.. -I../../include/compiler/msvc -I../../include/os/WIN32 -I../../include -IC:\Users\ultrafast\EPICS\base/include/compiler/msvc -IC:\Users\ultrafast\EPICS\base/include/os/WIN32 -IC:\Users\ultrafast\EPICS\base/include             -I../../ezca -I../..\..\MATLAB\R2022a/extern/include    ctrlC-polled.obj ../ctrlC-polled.c
perl -CSD C:/Users/ultrafast/EPICS/base/bin/windows-x64/mkmf.pl  -m multiEzca.d -I. -I../O.Common -I. -I. -I.. -I../../include/compiler/msvc -I../../include/os/WIN32 -I../../include -IC:\Users\ultrafast\EPICS\base/include/compiler/msvc -IC:\Users\ultrafast\EPICS\base/include/os/WIN32 -IC:\Users\ultrafast\EPICS\base/include             -I../../ezca -I../..\..\MATLAB\R2022a/extern/include    multiEzca.obj ../multiEzca.c
perl -CSD C:/Users/ultrafast/EPICS/base/bin/windows-x64/mkmf.pl  -m ini.d -I. -I../O.Common -I. -I. -I.. -I../../include/compiler/msvc -I../../include/os/WIN32 -I../../include -IC:\Users\ultrafast\EPICS\base/include/compiler/msvc -IC:\Users\ultrafast\EPICS\base/include/os/WIN32 -IC:\Users\ultrafast\EPICS\base/include             -I../../ezca -I../..\..\MATLAB\R2022a/extern/include    ini.obj ../ini.cc
The system cannot find the path specified.
perl -CSD -MExtUtils::Command -e rm_f gitstring.c.new
perl > gitstring.c.new -e "print(\"const char *gitRevisionString = \\\"labca_3_8_1 - ef74a39\\\";\n\")" > gitstring.c.new
perl -MFile::Compare -e 'exit( compare(@ARGV[0],@ARGV[1]) )' gitstring.c.new gitstring.c || (perl -CSD -MExtUtils::Command -e rm_f gitstring.c; perl -e 'rename("gitstring.c.new","gitstring.c")')
') was unexpected at this time.
cl -EHsc -GR          -DMATLAB_APP      -nologo -FC -D__STDC__=0 -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE    -Ox -GL -Oy-   -W3 -w44355 -w44344 -w44251 -D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING        -MD -DEPICS_BUILD_DLL -DEPICS_CALL_DLL -TP   -I. -I../O.Common -I. -I. -I.. -I../../include/compiler/msvc -I../../include/os/WIN32 -I../../include -IC:\Users\ultrafast\EPICS\base/include/compiler/msvc -IC:\Users\ultrafast\EPICS\base/include/os/WIN32 -IC:\Users\ultrafast\EPICS\base/include             -I../../ezca -I../..\..\MATLAB\R2022a/extern/include    -c ../ini.cc
ini.cc
C:\Program Files\LabCA\glue\ini.cc(3): warning C4005: 'MATLAB_APP': macro redefinition
C:\Program Files\LabCA\glue\ini.cc(3): note: 'MATLAB_APP' previously declared on the command line
cl          -DMATLAB_APP      -nologo -FC -D__STDC__=0 -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE    -Ox -GL -Oy-   -W3        -MD -DEPICS_BUILD_DLL -DEPICS_CALL_DLL     -I. -I../O.Common -I. -I. -I.. -I../../include/compiler/msvc -I../../include/os/WIN32 -I../../include -IC:\Users\ultrafast\EPICS\base/include/compiler/msvc -IC:\Users\ultrafast\EPICS\base/include/os/WIN32 -IC:\Users\ultrafast\EPICS\base/include             -I../../ezca -I../..\..\MATLAB\R2022a/extern/include    -c ../multiEzca.c
multiEzca.c
C:\Program Files\LabCA\glue\multiEzca.c(27): warning C4005: 'isnan': macro redefinition
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\corecrt_math.h(280): note: see previous definition of 'isnan'
C:\Program Files\MATLAB\R2022a\extern\include\mex.h(197): warning C4005: 'printf': macro redefinition
C:\Users\ultrafast\EPICS\base\include\epicsStdio.h(86): note: see previous definition of 'printf'
cl          -DMATLAB_APP      -nologo -FC -D__STDC__=0 -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE    -Ox -GL -Oy-   -W3        -MD -DEPICS_BUILD_DLL -DEPICS_CALL_DLL     -I. -I../O.Common -I. -I. -I.. -I../../include/compiler/msvc -I../../include/os/WIN32 -I../../include -IC:\Users\ultrafast\EPICS\base/include/compiler/msvc -IC:\Users\ultrafast\EPICS\base/include/os/WIN32 -IC:\Users\ultrafast\EPICS\base/include             -I../../ezca -I../..\..\MATLAB\R2022a/extern/include    -c ../ctrlC-polled.c
ctrlC-polled.c
make[2]: *** No rule to make target 'gitstring.c', needed by 'gitstring.obj'.  Stop.
make[2]: Leaving directory 'C:/Program Files/LabCA/glue/O.windows-x64'
make[1]: *** [C:\Users\ultrafast\EPICS\base/configure/RULES_ARCHS:58: install.windows-x64] Error 2
make[1]: Leaving directory 'C:/Program Files/LabCA/glue'
make: *** [C:\Users\ultrafast\EPICS\base/configure/RULES_DIRS:85: glue.install] Error 2

C:\Program Files\LabCA>make
The system cannot find the path specified.
fatal: not a git repository (or any of the parent directories): .git
C:/ProgramData/chocolatey/lib/make/tools/install/bin/make.exe -C ./configure install
make[1]: Entering directory 'C:/Program Files/LabCA/configure'
The system cannot find the path specified.
C:/ProgramData/chocolatey/lib/make/tools/install/bin/make.exe -C O.windows-x64 -f ../Makefile TOP=../.. \
    T_A=windows-x64 install
make[2]: Entering directory 'C:/Program Files/LabCA/configure/O.windows-x64'
The system cannot find the path specified.
perl -CSD C:/Users/ultrafast/EPICS/base/bin/windows-x64/convertRelease.pl checkRelease
make[2]: Leaving directory 'C:/Program Files/LabCA/configure/O.windows-x64'
make[1]: Leaving directory 'C:/Program Files/LabCA/configure'
C:/ProgramData/chocolatey/lib/make/tools/install/bin/make.exe -C ./ezca install
make[1]: Entering directory 'C:/Program Files/LabCA/ezca'
The system cannot find the path specified.
C:/ProgramData/chocolatey/lib/make/tools/install/bin/make.exe -C O.windows-x64 -f ../Makefile TOP=../.. \
    T_A=windows-x64 install
make[2]: Entering directory 'C:/Program Files/LabCA/ezca/O.windows-x64'
The system cannot find the path specified.
make[2]: Nothing to be done for 'install'.
make[2]: Leaving directory 'C:/Program Files/LabCA/ezca/O.windows-x64'
make[1]: Leaving directory 'C:/Program Files/LabCA/ezca'
C:/ProgramData/chocolatey/lib/make/tools/install/bin/make.exe -C ./glue install
make[1]: Entering directory 'C:/Program Files/LabCA/glue'
The system cannot find the path specified.
C:/ProgramData/chocolatey/lib/make/tools/install/bin/make.exe -C O.windows-x64 -f ../Makefile TOP=../.. \
    T_A=windows-x64 install
make[2]: Entering directory 'C:/Program Files/LabCA/glue/O.windows-x64'
The system cannot find the path specified.
perl -CSD C:/Users/ultrafast/EPICS/base/bin/windows-x64/mkmf.pl  -m gitstring.d -I. -I../O.Common -I. -I. -I.. -I../../include/compiler/msvc -I../../include/os/WIN32 -I../../include -IC:\Users\ultrafast\EPICS\base/include/compiler/msvc -IC:\Users\ultrafast\EPICS\base/include/os/WIN32 -IC:\Users\ultrafast\EPICS\base/include             -I../../ezca -I../..\..\MATLAB\R2022a/extern/include    gitstring.obj gitstring.c
The system cannot find the path specified.
cl          -DMATLAB_APP      -nologo -FC -D__STDC__=0 -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE    -Ox -GL -Oy-   -W3        -MD -DEPICS_BUILD_DLL -DEPICS_CALL_DLL     -I. -I../O.Common -I. -I. -I.. -I../../include/compiler/msvc -I../../include/os/WIN32 -I../../include -IC:\Users\ultrafast\EPICS\base/include/compiler/msvc -IC:\Users\ultrafast\EPICS\base/include/os/WIN32 -IC:\Users\ultrafast\EPICS\base/include             -I../../ezca -I../..\..\MATLAB\R2022a/extern/include    -c gitstring.c
gitstring.c
cl          -DMATLAB_APP      -nologo -FC -D__STDC__=0 -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE    -Ox -GL -Oy-   -W3        -MD -DEPICS_BUILD_DLL -DEPICS_CALL_DLL     -I. -I../O.Common -I. -I. -I.. -I../../include/compiler/msvc -I../../include/os/WIN32 -I../../include -IC:\Users\ultrafast\EPICS\base/include/compiler/msvc -IC:\Users\ultrafast\EPICS\base/include/os/WIN32 -IC:\Users\ultrafast\EPICS\base/include             -I../../ezca -I../..\..\MATLAB\R2022a/extern/include    -c ../mglue.c
mglue.c
link -nologo -subsystem:windows -dll -LTCG -incremental:no -opt:ref -release  -MACHINE:X64     ../..\..\MATLAB\R2022a/extern/lib/win64/microsoft/libut.lib ../..\..\MATLAB\R2022a/extern/lib/win64/microsoft/libmx.lib ../..\..\MATLAB\R2022a/extern/lib/win64/microsoft/libmex.lib  -out:mezcaglue.dll -implib:mezcaglue.lib     ini.obj multiEzca.obj ctrlC-polled.obj gitstring.obj mglue.obj        ../../lib/windows-x64/ezcamt.lib  C:\Users\ultrafast\EPICS\base/lib/windows-x64/ca.lib  C:\Users\ultrafast\EPICS\base/lib/windows-x64/Com.lib user32.lib
   Creating library mezcaglue.lib and object mezcaglue.exp
Generating code
Finished generating code
"Installing shared library ../../bin/windows-x64/mezcaglue.dll"
"Installing library ../../lib/windows-x64/mezcaglue.lib"
make[2]: Leaving directory 'C:/Program Files/LabCA/glue/O.windows-x64'
make[1]: Leaving directory 'C:/Program Files/LabCA/glue'
C:/ProgramData/chocolatey/lib/make/tools/install/bin/make.exe -C ./documentation install
make[1]: Entering directory 'C:/Program Files/LabCA/documentation'
The system cannot find the path specified.
process_begin: CreateProcess(NULL, sed -n -e "s/\(.*[^b]subsection.*[{][ \t]*\)\(lca[a-zA-Z0-9]*\).*/\2/gp" manual.tex, ...) failed.
Makefile:61: pipe: No error
process_begin: CreateProcess(NULL, sed -n -e "s/\(.*[^b]subsection.*[{][ \t]*\)\(lca[a-zA-Z0-9]*\)\(,\slca[a-zA-Z0-9]*\).*/\2/gp" manual.tex, ...) failed.
Makefile:68: pipe: No error
process_begin: CreateProcess(NULL, sed -n -e "s/\(.*[^b]subsection.*[{][ \t]*\)\(lca[a-zA-Z0-9]*\)\(,\s\)\(lca[a-zA-Z0-9]*\).*/\4/gp" manual.tex, ...) failed.
Makefile:70: pipe: No error
make[1]: 'install' is up to date.
make[1]: Leaving directory 'C:/Program Files/LabCA/documentation'
C:/ProgramData/chocolatey/lib/make/tools/install/bin/make.exe -C ./matlab install
make[1]: Entering directory 'C:/Program Files/LabCA/matlab'
The system cannot find the path specified.
perl -CSD C:/Users/ultrafast/EPICS/base/bin/windows-x64/makeMakefile.pl O.windows-x64 ../..
perl -CSD -MExtUtils::Command -e mkpath O.Common
C:/ProgramData/chocolatey/lib/make/tools/install/bin/make.exe -C O.windows-x64 -f ../Makefile TOP=../.. \
    T_A=windows-x64 install
make[2]: Entering directory 'C:/Program Files/LabCA/matlab/O.windows-x64'
The system cannot find the path specified.
../..\..\MATLAB\R2022a/bin/mex.bat  CXXFLAGS= -DMATLAB_APP   ../lcaGetNelem.c -I. -I../O.Common -I. -I. -I.. -I../../include/compiler/msvc -I../../include/os/WIN32 -I../../include -IC:\Users\ultrafast\EPICS\base/include/compiler/msvc -IC:\Users\ultrafast\EPICS\base/include/os/WIN32 -IC:\Users\ultrafast\EPICS\base/include             -I../../ezca -I../../glue    LDFLAGS=" \$LDFLAGS"   ../../lib/windows-x64/mezcaglue.lib  ../../lib/windows-x64/ezcamt.lib  C:\Users\ultrafast\EPICS\base/lib/windows-x64/ca.lib  C:\Users\ultrafast\EPICS\base/lib/windows-x64/Com.lib  ../../lib/windows-x64/ezcamt.lib  C:\Users\ultrafast\EPICS\base/lib/windows-x64/ca.lib  C:\Users\ultrafast\EPICS\base/lib/windows-x64/Com.lib netapi32.lib
Building with 'Microsoft Visual C++ 2022 (C)'.
   Creating library lcaGetNelem.lib and object lcaGetNelem.exp
lcaGetNelem.obj : error LNK2019: unresolved external symbol lcaMexGblInit referenced in function mexFunction
lcaGetNelem.mexw64 : fatal error LNK1120: 1 unresolved externals


make[2]: *** [../Makefile:116: lcaGetNelem.mexw64] Error -1
make[2]: Leaving directory 'C:/Program Files/LabCA/matlab/O.windows-x64'
make[1]: *** [C:\Users\ultrafast\EPICS\base/configure/RULES_ARCHS:58: install.windows-x64] Error 2
make[1]: Leaving directory 'C:/Program Files/LabCA/matlab'
make: *** [C:\Users\ultrafast\EPICS\base/configure/RULES_DIRS:85: matlab.install] Error 2
```

**Comment by FreddieAkeroyd** [comment]
Hi @devilkingsatan666 i hadn't seen this issue until now when i was creating a PR, I had been trying to fix the same problems following a post on the epics tech-talk mailing list. You should hopefully find #8 fixes both problems you have encountered.
